#!/bin/bash

#SBATCH --job-name=LFR_DMoN_DICE        # Job name for the array
#SBATCH --partition=gpu-debug             # Partition (queue) name
#SBATCH --output=filename_%A_%a.txt      # Output file for stdout (%A: array job ID, %a: task ID)
#SBATCH --error=filename_%A_%a.err       # Output file for stderr (%A: array job ID, %a: task ID)
#SBATCH --mail-type=ALL                 # Email notification for job events
#SBATCH --mail-user=dmanato@iu.edu      # Email address to receive notifications
#SBATCH --nodes=1                       # Number of nodes
#SBATCH --ntasks-per-node=1             # Number of tasks per node
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-task=16              # Number of CPU cores per task
#SBATCH --time=1:00:00                 # Wall clock time limit
#SBATCH --mem=100G                      # Memory limit per node
#SBATCH -A r01712                       # Account (project) allocation
#SBATCH --array=0                  # Number of tasks in the array (0 to 7, 8 tasks in total)

# Load any required modules
module load cudatoolkit
# module load pytorch/gpu
module load python/gpu/3.11.5

# Activate a virtual environment if needed

# Go to the directory where the script is located
cd gnn-clustering-attack-defense

# Print the hostname and GPU information
echo "Running on $(hostname)"
nvidia-smi


# Run your program with parameters
# srun python test.py 
# srun python run_experiments.py --sigma_c_values 1 --mu_values 0.01  --b_percentages 1 --min_community 50 --seed 41 --outfile_csv test_bigred200_min_community.csv
# srun python run_experiments.py --mu_values 0.2 --outfile_csv full_bigred200_mu02.csv 
# srun python run_experiments.py --mu_values 0.3 0.4 0.5  --outfile_csv full_bigred200_mu05.csv 

srun python run_experiments.py --sigma_c_values 0.1 --mu_values 0.01 --realizations 1 --min_community 60 --seed 7 --outfile_csv test_dicecdhd_sigma01_mu001_min_com60.csv